# Generated by Django 2.0.4 on 2018-04-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='category',
            new_name='test_category',
        ),
    ]
