# Generated by Django 2.0.4 on 2018-04-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplans',
            name='phase',
            field=models.CharField(choices=[('ACPT', 'Acceptance'), ('BBFV', 'Building Block Functional Verification'), ('SDV', 'System Design Verification'), ('SIT', 'System Integration Test'), ('REGRESS', 'POST-GA Regression')], default='Acceptance', max_length=32),
        ),
    ]
